#!/bin/bash

export $(grep -v '^#' .env | xargs)

docker run -d -p $HOST_PORT:$APPLICATION_PORT --mount source=autovod_vol,target=/app/cache --mount source=autovod_db,target=/app/data/db.sqlite autovod